# Generated by Django 3.1 on 2021-01-30 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('upload_time', models.DateTimeField(default=datetime.datetime(2021, 1, 30, 15, 30, 10, 412383, tzinfo=utc))),
            ],
        ),
    ]
