# Generated by Django 3.1 on 2021-01-30 18:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_auto_20210130_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 30, 18, 40, 7, 948347, tzinfo=utc)),
        ),
    ]
