# Generated by Django 3.1 on 2021-01-31 08:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_auto_20210131_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('audiobook_name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Narrator', models.CharField(max_length=100)),
                ('upload_time', models.DateTimeField(default=datetime.datetime(2021, 1, 31, 8, 20, 4, 389578, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('podcast_name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('Host', models.CharField(max_length=100)),
                ('Participants', models.CharField(max_length=1100)),
                ('upload_time', models.DateTimeField(default=datetime.datetime(2021, 1, 31, 8, 20, 4, 389578, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 31, 8, 20, 4, 389578, tzinfo=utc)),
        ),
    ]
