# Generated by Django 3.1 on 2021-01-31 08:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_auto_20210131_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiobook',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='audiobook',
            old_name='Narrator',
            new_name='narrator',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='Host',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='Participants',
            new_name='participants',
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 31, 8, 29, 22, 736411, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 31, 8, 29, 22, 736411, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='song',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 31, 8, 29, 22, 736411, tzinfo=utc)),
        ),
    ]
