# Generated by Django 3.1 on 2021-01-31 16:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0007_auto_20210131_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 31, 16, 22, 10, 955575, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 31, 16, 22, 10, 954574, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='song',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 31, 16, 22, 10, 954574, tzinfo=utc)),
        ),
    ]
